name = "DeadSFU"
license = "MIT"

licenselink = "https://github.com/x186k/deadsfu/blob/main/LICENSE"
description = "DeadSFU is for building Simple, Scalable WebRTC Systems."
homepage = "https://deadsfu.com/"

tags = ["sfu", "webrtc", "broadcasting", "streaming", "video", "real-time", "low-latency"]
features = ["scalable", "obs", "open-source", "mit", "free", "docker", "kubernetes", "digital ocean"]
min_version = "0.75.0"

[author]
  name = "Cameron Elliott"
  homepage = "https://cameronelliott.com/"
