
# Test and build your Hyas project
# For more information see: https://henkverlinde.com/continuous-integration-workflow-for-your-hyas-project/

name: github pages

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:

    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x


    - name: Set up Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        hugo-version: '0.83.1'
        extended: true
    
    - name: Check install Hugo
      run: hugo version

    - name: Install dependencies
      run: npm ci

    - name: Run Hyas test script
      run: npm test

    - name: Build production website
      run: npm run build


    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        destination_dir: 3419512222
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
